groups:
  - name: deployment-failures
    rules:
      - alert: deployment-generation-mismatch
        labels:
          group: deployment-failures
          receiver: slack
          severity: low
        annotations:
          dashboard: /d/not-implemented
          summary:
            Deployment generation for {{ $labels.namespace }}/{{ $labels.deployment }} 
            does not match. This indicates that the Deployment has failed but has
            not been rolled back.
        expr: |
          kube_deployment_status_observed_generation{job="kube-state-metrics"}
            !=
          kube_deployment_metadata_generation{job="kube-state-metrics"}
        for: 15m
      - alert: deployment-replicas-mismatch
        labels:
          group: deployment-failures
          receiver: slack
          severity: medium
        annotations:
          dashboard: /d/not-implemented
          summary:
            Deployment {{ $labels.namespace }}/{{ $labels.deployment }} has not
            matched the expected number of replicas for longer than an hour.
        expr: |
          kube_deployment_spec_replicas{job="kube-state-metrics"}
            !=
          kube_deployment_status_replicas_available{job="kube-state-metrics"}
        for: 1h
