{
 "title": "Basic Resources",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ns", "label": "namespace", "query": "kube_namespace_labels" }
  ]
 },
 "panels": [
  {
   "title": "Pod Resource Requests (CPU)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$ns\"})",
     "legendFormat": "$ns"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(kube_node_info)" }
   ]
  },
  {
   "title": "Unscheduled Pods",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_replicaset_status_replicas) - sum(kube_replicaset_status_ready_replicas)"
    }
   ]
  },
  {
   "title": "Available Node %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\"})/sum(kube_node_info)*100"
    }
   ]
  },
  {
   "title": "Pod Resource Limits - Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$ns\"}) ",
     "legendFormat": "$ns"
    }
   ]
  },
  {
   "title": "Certificate Expiry",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "max((certmanager_certificate_expiration_timestamp_seconds - time()) / 60 / 60 / 24) by (exported_namespace)"
    }
   ]
  }
 ]
}