---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: node-exporter
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
  privileged: false
  allowPrivilegeEscalation: false
  hostNetwork: true
  hostPID: true
  hostPorts:
  - min: 9100
    max: 9100
  volumes:
  - hostPath
  - secret
  allowedHostPaths:
  - pathPrefix: '/proc'
  - pathPrefix: '/sys'
  seLinux:
    rule: RunAsAny
  runAsUser:
    rule: MustRunAsNonRoot
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
