---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:node-exporter
  namespace: metrics
roleRef:
  kind: Role
  name: psp:node-exporter
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: node-exporter
  namespace: metrics
