---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp:node-exporter
  namespace: metrics
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - node-exporter
  verbs:
  - use
