---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: mw-prometheus
  namespace: monitoring
  labels:
    prometheus: mw-prometheus
spec:
  replicas: 2
  retention: 180d
  scrapeInterval: 10s
  evaluationInterval: 30s
  serviceAccountName: mw-prometheus
  # serviceMonitorNamespaceSelector:
  #   matchLabels:
  #     prometheus-namespace: monitoring
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  # podMonitorNamespaceSelector:
  #   matchLabels:
  #     prometheus-namespace: monitoring
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  # ruleNamespaceSelector:
  #   matchLabels:
  #     prometheus-namespace: monitoring
  ruleNamespaceSelector: {}
  ruleSelector: {}
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              prometheus: mw-prometheus
          topologyKey: failure-domain.beta.kubernetes.io/zone
  storage:
    volumeClaimTemplate:
      metadata:
        name: prometheus-storage
        labels:
          prometheus: mw-prometheus
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: prometheus-ssd
        resources:
          requests:
            storage: 20Gi
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 250Mi
  securityContext:
    fsGroup: 2000
    runAsUser: 1000
    runAsNonRoot: true
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager-main
      port: web
  baseImage: quay.io/prometheus/prometheus
  version: v2.12.0
  # tolerations:
  # - key: app
  #   operator: Equal
  #   value: prometheus
  #   effect: NoSchedule
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: prometheus-ssd
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
kind: PodDisruptionBudget
apiVersion: policy/v1beta1
metadata:
  name: prometheus-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: prometheus
