---
apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: mw-prometheus
  name: mw-prometheus
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9090
    targetPort: web
  selector:
    prometheus: mw-prometheus
