---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-operator-controller-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
