---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: mw
spec:
  podMetadata:
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  replicas: 1
  serviceAccountName: prometheus
  externalUrl: https://alertmanager.alexos.dev
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              alertmanager: mw
          topologyKey: failure-domain.beta.kubernetes.io/zone
  resources:
    requests:
      memory: 50Mi
      cpu: 10m
    limits:
      memory: 100Mi
      cpu: 100m
  securityContext:
    fsGroup: 2000
    runAsUser: 1000
    runAsNonRoot: true
  image: quay.io/prometheus/alertmanager:v0.24.0
  logFormat: json
  logLevel: debug
  nodeSelector:
    cloud.google.com/gke-spot: "true"
  tolerations:
  - effect: NoSchedule
    key: cloud.google.com/gke-spot
    operator: Equal
    value: "true"