---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alertmanager
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
    - host: alertmanager.alexos.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: alertmanager-mw
                port:
                  name: web
  tls:
    - secretName: alertmanager-tls
      hosts:
        - alertmanager.alexos.dev
