---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: alertmanager
spec:
  parentRefs:
  - kind: Gateway
    name: shared-gateway
    namespace: ingress
  hostnames:
  - alertmanager.alexos.dev
  rules:
  - backendRefs:
    - name: alertmanager-operated
      port: 9093
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: lb-healthcheck
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    logConfig:
      enabled: false
    config:
      type: HTTP
      httpHealthCheck:
        port: 9093
        requestPath: /-/healthy
  targetRef:
    group: ""
    kind: Service
    name: alertmanager-operated
---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: alertmanager-iap
spec:
  default:
    iap:
      enabled: true
      oauth2ClientSecret:
        name: iap-client
      clientID: 538016369232-2v8f81i0bl6ij2a23rdcmno7lok5jkq9.apps.googleusercontent.com
  targetRef:
    group: ""
    kind: Service
    name: alertmanager-operated
