---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus

commonLabels:
  app: alertmanager-mw
  alertmanager: mw

resources:
- alertmanager.yaml
# - ingress.yaml    # disabled until build auth into it
- pdb.yaml
- secret-config.yaml
- service.yaml
- service-monitor.yaml
