---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus

commonLabels:
  alertmanager: mw

resources:
- alertmanager.yaml
- pdb.yaml
- secret-config.yaml
- service.yaml
- service-monitor.yaml
