---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metrics

commonLabels:
  alertmanager: mw

resources:
- alertmanager.yaml
- ingress.yaml
- secret-config.yaml
- service.yaml
- service-monitor.yaml
