---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-mw
  labels:
    alertmanager: mw
stringData:

  priority.tmpl: |
    {{- define "__priority" -}}
    {{ .CommonLabels.priority }}
    {{- end -}}

  alert_title.tmpl: |
    {{- define "__alert_title" -}}
    [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification
    {{- end -}}

  label_json_url_encoded.tmpl: |
    {{- define "__label_json_url_encoded" -}}
    %7B{{-   range $index, $label := .Labels.SortedPairs -}}
    {{-     if $index -}}%2C%20{{ end -}}
    {{-     urlquery $label.Name -}}%3D%22{{- urlquery $label.Value -}}%22
    {{-   end -}}%7D
    {{- end -}}

  silence_link.tmpl: |
    {{- define "__silence_link" -}}
    https://alertmanager.alexos.dev/#/silences/new?filter={{ template "__label_json_url_encoded" . }}
    {{- end -}}

  alert_text.tmpl: |
    {{ define "__slack_text" }}
    {{- range .Alerts -}}
    {{- "" }}• {{ .Annotations.summary }}
    {{ end }}

    {{- range .Alerts }}
    ---
    *Summary:* {{ .Annotations.summary }} - `{{ .Labels.priority }}`
    {{ if .Annotations.description }}*Description:* {{ .Annotations.description }}
    {{ end -}}
    <{{ template "__silence_link" . }}|*Silence* :no_bell:> | <{{ .Annotations.runbook }}|*Runbook* :spiral_note_pad:> | <{{ .GeneratorURL }}|*Graph* :chart_with_upwards_trend:>
    {{- if .Annotations.dashboard }} | <https://grafana.alexos.dev/{{ .Annotations.dashboard }}
    {{- $contains_param := (match "\\?" .Annotations.dashboard ) -}}
    {{-   if $contains_param -}}
      &
    {{-   else -}}
      ?
    {{-   end -}}
          var-namespace={{ .Labels.namespace }}|*Dashboard* :chart_with_downwards_trend:>
    {{- end }}
    *Details:*
    {{ range .Labels.SortedPairs }}• *{{ .Name }}:* `{{ .Value }}`
    {{ end }}
    {{ end -}}
    {{ end -}}

  alertmanager.yaml: |
    ---
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.sendgrid.net:587'
      smtp_from: 'alertmanager@alexos.dev'
      smtp_hello: 'alertmanager.alexos.dev'
      smtp_auth_username: 'apikey'
      smtp_auth_password: '$SENDGRID_KEY'
      smtp_require_tls: true
    templates:
    - '*.tmpl'
    - '/etc/alertmanager/secrets/**/*.tmpl'
    route:
      group_by: [alertname]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      receiver: default
      routes:
      - receiver: default
        group_by: [group]
        matchers:
        - receiver="default"
      - receiver: email
        group_by: [group]
        matchers:
        - receiver="email"
    receivers:
      - name: email
        email_configs:
          - to: 'site@alexos.dev'
            send_resolved: true
      - name: default
        webhook_configs:
        - url: 'http://alertmanager:30500/'
