---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-mw
stringData:
  alertmanager.yaml: |
    ---
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.postmarkapp.com:587'
      smtp_from: 'alertmanager@alexos.dev'
      smtp_hello: 'alertmanager.alexos.dev'
      smtp_auth_username: '$POSTMARK_ACCESS_KEY'
      smtp_auth_password: '$POSTMARK_SECRET_KEY'
      smtp_require_tls: true
    templates:
    - '*.tmpl'
    - '/etc/alertmanager/secrets/**/*.tmpl'
    route:
      group_by: [alertname]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      receiver: default
      routes:
      - receiver: email
        group_by: [group]
        matchers:
        - receiver="email"
      - receiver: slack
        group_by: [group,severity]
        matchers:
        - receiver="slack"
    receivers:
      - name: slack
        slack_configs:
        - channel: #operability
          send_resolved: true
          api_url: $SLACK_WEBHOOK_URL
          title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification'
          text: >-
            {{ range .Alerts }}
              *Alert:* {{ .Annotations.summary }}
              *Severity:* {{ .Labels.severity }}
              *Dashboard:* <https://grafana.alexos.dev/{{ .Annotations.dashboard }}|:chart_with_upwards_trend:>
              *Details:*
              {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
              {{ end }}
            {{ end }}
      - name: email
        email_configs:
          - to: 'site@alexos.dev'
            send_resolved: true
      - name: default
        webhook_configs:
        - url: 'http://alertmanager-test-webhook:8000/webhook'
