---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-mw
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9093
      protocol: TCP
      targetPort: web
  selector:
    alertmanager: mw
