---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alertmanager
spec:
  jobLabel: alertmanager
  selector:
    matchLabels:
      alertmanager: mw
  namespaceSelector:
    matchNames:
      - metrics
  endpoints:
    - port: web
      interval: 30s
      path: /metrics
