---
# Source: grafana-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mw-grafana-operator
  namespace: metrics
  labels:
    helm.sh/chart: grafana-operator-v5.12.0
    app.kubernetes.io/name: grafana-operator
    app.kubernetes.io/instance: mw
    app.kubernetes.io/version: "v5.12.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: grafana-operator
    app.kubernetes.io/component: operator
automountServiceAccountToken: true
---
# Source: grafana-operator/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: metrics
  name: mw-grafana-operator
  labels:
    helm.sh/chart: grafana-operator-v5.12.0
    app.kubernetes.io/name: grafana-operator
    app.kubernetes.io/instance: mw
    app.kubernetes.io/version: "v5.12.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: grafana-operator
    app.kubernetes.io/component: operator
rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    - persistentvolumeclaims
    - secrets
    - serviceaccounts
    - services
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - get
    - list
    - patch
    - watch
  - apiGroups:
    - apps
    resources:
    - deployments
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - grafana.integreatly.org
    resources:
    - grafanaalertrulegroups
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - grafana.integreatly.org
    resources:
    - grafanaalertrulegroups/finalizers
    verbs:
    - update
  - apiGroups:
    - grafana.integreatly.org
    resources:
    - grafanaalertrulegroups/status
    verbs:
    - get
    - patch
    - update
  - apiGroups:
    - grafana.integreatly.org
    resources:
    - grafanacontactpoints
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - grafana.integreatly.org
    resources:
    - grafanacontactpoints/finalizers
    verbs:
    - update
  - apiGroups:
    - grafana.integreatly.org
    resources:
    - grafanacontactpoints/status
    verbs:
    - get
    - patch
    - update
  - apiGroups:
    - grafana.integreatly.org
    resources:
    - grafanadashboards
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - grafana.integreatly.org
    resources:
    - grafanadashboards/finalizers
    verbs:
    - update
  - apiGroups:
    - grafana.integreatly.org
    resources:
    - grafanadashboards/status
    verbs:
    - get
    - patch
    - update
  - apiGroups:
    - grafana.integreatly.org
    resources:
    - grafanadatasources
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - grafana.integreatly.org
    resources:
    - grafanadatasources/finalizers
    verbs:
    - update
  - apiGroups:
    - grafana.integreatly.org
    resources:
    - grafanadatasources/status
    verbs:
    - get
    - patch
    - update
  - apiGroups:
    - grafana.integreatly.org
    resources:
    - grafanafolders
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - grafana.integreatly.org
    resources:
    - grafanafolders/finalizers
    verbs:
    - update
  - apiGroups:
    - grafana.integreatly.org
    resources:
    - grafanafolders/status
    verbs:
    - get
    - patch
    - update
  - apiGroups:
    - grafana.integreatly.org
    resources:
    - grafananotificationpolicies
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - grafana.integreatly.org
    resources:
    - grafananotificationpolicies/finalizers
    verbs:
    - update
  - apiGroups:
    - grafana.integreatly.org
    resources:
    - grafananotificationpolicies/status
    verbs:
    - get
    - patch
    - update
  - apiGroups:
    - grafana.integreatly.org
    resources:
    - grafanas
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - grafana.integreatly.org
    resources:
    - grafanas/finalizers
    verbs:
    - update
  - apiGroups:
    - grafana.integreatly.org
    resources:
    - grafanas/status
    verbs:
    - get
    - patch
    - update
  - apiGroups:
    - networking.k8s.io
    resources:
    - ingresses
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
---
# Source: grafana-operator/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mw-grafana-operator
  namespace: metrics
  labels:
    helm.sh/chart: grafana-operator-v5.12.0
    app.kubernetes.io/name: grafana-operator
    app.kubernetes.io/instance: mw
    app.kubernetes.io/version: "v5.12.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: grafana-operator
    app.kubernetes.io/component: operator
subjects:
  - kind: ServiceAccount
    name: mw-grafana-operator
    namespace: metrics
roleRef:
  kind: Role
  name: mw-grafana-operator
  apiGroup: rbac.authorization.k8s.io
---
# Source: grafana-operator/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mw-grafana-operator-metrics-service
  namespace: metrics
  labels:
    helm.sh/chart: grafana-operator-v5.12.0
    app.kubernetes.io/name: grafana-operator
    app.kubernetes.io/instance: mw
    app.kubernetes.io/version: "v5.12.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: grafana-operator
    app.kubernetes.io/component: operator
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: 8888
      targetPort: pprof
      protocol: TCP
      name: pprof
  selector:
    app.kubernetes.io/name: grafana-operator
    app.kubernetes.io/instance: mw
---
# Source: grafana-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mw-grafana-operator
  namespace: metrics
  labels:
    helm.sh/chart: grafana-operator-v5.12.0
    app.kubernetes.io/name: grafana-operator
    app.kubernetes.io/instance: mw
    app.kubernetes.io/version: "v5.12.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: grafana-operator
    app.kubernetes.io/component: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-operator
      app.kubernetes.io/instance: mw
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana-operator
        app.kubernetes.io/instance: mw
        app.kubernetes.io/component: operator
    spec:
      serviceAccountName: mw-grafana-operator
      containers:
        - name: grafana-operator
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          image: "ghcr.io/grafana/grafana-operator:v5.12.0"
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: metrics
            - name: WATCH_NAMESPACE_SELECTOR
              value: ""
              
          args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=0.0.0.0:9090
            - --pprof-addr=0.0.0.0:8888
          volumeMounts:
            - name: dashboards-dir
              mountPath: /tmp/dashboards
          ports:
            - containerPort: 9090
              name: metrics
              protocol: TCP
            - containerPort: 8888
              name: pprof
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              memory: 100Mi
      volumes:
        - name: dashboards-dir
          emptyDir: {}
