---
apiVersion: 1
datasources:
  - access: proxy
    isDefault: true
    name: prometheus
    type: prometheus
    url: http://prometheus-operated.prometheus.svc:9090
    version: 1
    editable: false
    orgId: 1
  - access: proxy
    isDefault: false
    name: loki
    type: loki
    url: http://loki.loki:3100
    version: 1
    editable: false
    orgId: 1
