---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alexos
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: alexos
  namespaceSelector:
    matchNames:
      - alexos
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
