---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alexandlou
  namespace: metrics
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: alexandlou
  namespaceSelector:
    matchNames:
      - alexandlou
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
