---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alexmoss
  namespace: metrics
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: alexmoss
  namespaceSelector:
    matchNames:
      - alexmoss
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
