---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: contact-handler
  namespace: metrics
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: contact-handler
  namespaceSelector:
    matchNames:
      - contact
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
