---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kyverno
  namespace: metrics
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: metrics-port
  jobLabel: kyverno
  namespaceSelector:
    matchNames:
    - kyverno
  selector:
    matchLabels:
      app.kubernetes.io/instance: kyverno
      app.kubernetes.io/name: kyverno
