---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: metrics
spec:
  selector:
    matchLabels:
      app: node-exporter
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: node-exporter
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      name: node-exporter
    spec:
      tolerations:
        - effect: NoExecute
          operator: Exists
        - effect: NoSchedule
          operator: Exists
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: node-exporter
      automountServiceAccountToken: false
      hostNetwork: true
      hostPID: true
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: node-exporter
                topologyKey: kubernetes.io/hostname
      containers:
        - image: quay.io/prometheus/node-exporter:v1.9.1
          args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --web.disable-exporter-metrics
            - --collector.cpu
            - --collector.diskstats
            - --collector.filefd
            - --collector.filesystem
            - --collector.loadavg
            - --collector.meminfo
            - --collector.netdev
            - --collector.netstat
            - --collector.stat
            - --collector.time
            - --collector.vmstat
            - --no-collector.arp
            - --no-collector.bcache
            - --no-collector.bonding
            - --no-collector.conntrack
            - --no-collector.cpufreq
            - --no-collector.edac
            - --no-collector.entropy
            - --no-collector.hwmon
            - --no-collector.infiniband
            - --no-collector.ipvs
            - --no-collector.mdadm
            - --no-collector.netclass
            - --no-collector.nfs
            - --no-collector.nfsd
            - --no-collector.pressure
            - --no-collector.sockstat
            - --no-collector.textfile
            - --no-collector.timex
            - --no-collector.uname
            - --no-collector.xfs
            - --no-collector.zfs
          name: node-exporter
          ports:
            - containerPort: 9100
              hostPort: 9100
              name: scrape
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
              ephemeral-storage: 50Mi
            limits:
              memory: 40Mi
              cpu: 50m
              ephemeral-storage: 50Mi
          securityContext:
            capabilities:
              drop:
              - ALL
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: proc
              readOnly: true
              mountPath: /host/proc
            - name: sys
              readOnly: true
              mountPath: /host/sys
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
