---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: mw
    role: k8s-recording-rules
  name: k8s-recording-rules
  namespace: metrics
spec:
  groups:
    - name: k8s.rules
      rules:
        - expr: |
            sum by (namespace, pod, container) (
              rate(container_cpu_usage_seconds_total{job="kubelet", image!="", container!="POD"}[5m])
            )
          record: namespace_pod_container:container_cpu_usage_seconds_total:sum_rate
        - expr: |
            sum by (namespace, label_name) (
                sum(kube_pod_container_resource_requests_memory{job="kube-state-metrics"} * on (endpoint, instance, job, namespace, pod, service) group_left(phase) (kube_pod_status_phase{phase=~"^(Pending|Running)$"} == 1)) by (namespace, pod)
              * on (namespace, pod)
                group_left(label_name) kube_pod_labels{job="kube-state-metrics"}
            )
          record: namespace:kube_pod_container_resource_requests_memory:sum
        - expr: |
            sum by (namespace, label_name) (
                sum(kube_pod_container_resource_requests{resource="cpu", job="kube-state-metrics"} * on (endpoint, instance, job, namespace, pod, service) group_left(phase) (kube_pod_status_phase{phase=~"^(Pending|Running)$"} == 1)) by (namespace, pod)
              * on (namespace, pod)
                group_left(label_name) kube_pod_labels{job="kube-state-metrics"}
            )
          record: namespace:kube_pod_container_resource_requests_cpu:sum
    - name: node.rules
      rules:
        - expr: sum(min(kube_pod_info) by (node))
          record: ":kube_pod_info_node_count:"
        - expr: |
            max(label_replace(kube_pod_info{job="kube-state-metrics"}, "pod", "$1", "pod", "(.*)")) by (node, namespace, pod)
          record: "node_namespace_pod:kube_pod_info:"
        - expr: |
            count by (node) (sum by (node, cpu) (
              node_cpu_seconds_total{job="node-exporter"}
            * on (namespace, pod) group_left(node)
              node_namespace_pod:kube_pod_info:
            ))
          record: node:node_num_cpu:sum
        - expr: |
            1 - avg(rate(node_cpu_seconds_total{job="node-exporter",mode="idle"}[1m]))
          record: :node_cpu_utilisation:avg1m
        - expr: |
            1 - avg by (node) (
              rate(node_cpu_seconds_total{job="node-exporter",mode="idle"}[1m])
            * on (namespace, pod) group_left(node)
              node_namespace_pod:kube_pod_info:)
          record: node:node_cpu_utilisation:avg1m
        - expr: |
            node:node_cpu_utilisation:avg1m
              *
            node:node_num_cpu:sum
              /
            scalar(sum(node:node_num_cpu:sum))
          record: node:cluster_cpu_utilisation:ratio
        - expr: |
            sum(node_load1{job="node-exporter"})
            /
            sum(node:node_num_cpu:sum)
          record: ":node_cpu_saturation_load1:"
        - expr: |
            sum by (node) (
              node_load1{job="node-exporter"}
            * on (namespace, pod) group_left(node)
              node_namespace_pod:kube_pod_info:
            )
            /
            node:node_num_cpu:sum
          record: "node:node_cpu_saturation_load1:"
        - expr: |
            1 -
            sum(node_memory_MemFree_bytes{job="node-exporter"} + node_memory_Cached_bytes{job="node-exporter"} + node_memory_Buffers_bytes{job="node-exporter"})
            /
            sum(node_memory_MemTotal_bytes{job="node-exporter"})
          record: ":node_memory_utilisation:"
        - expr: |
            sum by (node) (
              (node_memory_MemFree_bytes{job="node-exporter"} + node_memory_Cached_bytes{job="node-exporter"} + node_memory_Buffers_bytes{job="node-exporter"})
              * on (namespace, pod) group_left(node)
                node_namespace_pod:kube_pod_info:
            )
          record: node:node_memory_bytes_available:sum
        - expr: |
            sum by (node) (
              node_memory_MemTotal_bytes{job="node-exporter"}
              * on (namespace, pod) group_left(node)
                node_namespace_pod:kube_pod_info:
            )
          record: node:node_memory_bytes_total:sum
        - expr: |
            (node:node_memory_bytes_total:sum - node:node_memory_bytes_available:sum)
            /
            scalar(sum(node:node_memory_bytes_total:sum))
          record: node:cluster_memory_utilisation:ratio
        - expr: |
            1e3 * sum(
              (rate(node_vmstat_pgpgin{job="node-exporter"}[1m])
             + rate(node_vmstat_pgpgout{job="node-exporter"}[1m]))
            )
          record: :node_memory_swap_io_bytes:sum_rate
        - expr: |
            1 -
            sum by (node) (
              (node_memory_MemFree_bytes{job="node-exporter"} + node_memory_Cached_bytes{job="node-exporter"} + node_memory_Buffers_bytes{job="node-exporter"})
            * on (namespace, pod) group_left(node)
              node_namespace_pod:kube_pod_info:
            )
            /
            sum by (node) (
              node_memory_MemTotal_bytes{job="node-exporter"}
            * on (namespace, pod) group_left(node)
              node_namespace_pod:kube_pod_info:
            )
          record: "node:node_memory_utilisation:"
        - expr: |
            1e3 * sum by (node) (
              (rate(node_vmstat_pgpgin{job="node-exporter"}[1m])
             + rate(node_vmstat_pgpgout{job="node-exporter"}[1m]))
             * on (namespace, pod) group_left(node)
               node_namespace_pod:kube_pod_info:
            )
          record: node:node_memory_swap_io_bytes:sum_rate
        - expr: |
            avg(irate(node_disk_io_time_seconds_total{job="node-exporter",device=~"nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+"}[1m]))
          record: :node_disk_utilisation:avg_irate
        - expr: |
            avg by (node) (
              irate(node_disk_io_time_seconds_total{job="node-exporter",device=~"nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+"}[1m])
            * on (namespace, pod) group_left(node)
              node_namespace_pod:kube_pod_info:
            )
          record: node:node_disk_utilisation:avg_irate
        - expr: |
            avg(irate(node_disk_io_time_weighted_seconds_total{job="node-exporter",device=~"nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+"}[1m]))
          record: :node_disk_saturation:avg_irate
        - expr: |
            avg by (node) (
              irate(node_disk_io_time_weighted_seconds_total{job="node-exporter",device=~"nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+"}[1m])
            * on (namespace, pod) group_left(node)
              node_namespace_pod:kube_pod_info:
            )
          record: node:node_disk_saturation:avg_irate
        - expr: |
            max by (instance, namespace, pod, device) ((node_filesystem_size_bytes{fstype=~"ext[234]|btrfs|xfs|zfs"}
            - node_filesystem_avail_bytes{fstype=~"ext[234]|btrfs|xfs|zfs"})
            / node_filesystem_size_bytes{fstype=~"ext[234]|btrfs|xfs|zfs"})
          record: "node:node_filesystem_usage:"
        - expr: |
            max by (instance, namespace, pod, device) (node_filesystem_avail_bytes{fstype=~"ext[234]|btrfs|xfs|zfs"} / node_filesystem_size_bytes{fstype=~"ext[234]|btrfs|xfs|zfs"})
          record: "node:node_filesystem_avail:"
        - expr: |
            sum(irate(node_network_receive_bytes_total{job="node-exporter",device!~"veth.+"}[1m])) +
            sum(irate(node_network_transmit_bytes_total{job="node-exporter",device!~"veth.+"}[1m]))
          record: :node_net_utilisation:sum_irate
        - expr: |
            sum by (node) (
              (irate(node_network_receive_bytes_total{job="node-exporter",device!~"veth.+"}[1m]) +
              irate(node_network_transmit_bytes_total{job="node-exporter",device!~"veth.+"}[1m]))
            * on (namespace, pod) group_left(node)
              node_namespace_pod:kube_pod_info:
            )
          record: node:node_net_utilisation:sum_irate
        - expr: |
            sum(irate(node_network_receive_drop_total{job="node-exporter",device!~"veth.+"}[1m])) +
            sum(irate(node_network_transmit_drop_total{job="node-exporter",device!~"veth.+"}[1m]))
          record: :node_net_saturation:sum_irate
        - expr: |
            sum by (node) (
              (irate(node_network_receive_drop_total{job="node-exporter",device!~"veth.+"}[1m]) +
              irate(node_network_transmit_drop_total{job="node-exporter",device!~"veth.+"}[1m]))
            * on (namespace, pod) group_left(node)
              node_namespace_pod:kube_pod_info:
            )
          record: node:node_net_saturation:sum_irate
