---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  namespace: metrics
  labels:
    prometheus: mw
spec:
  jobLabel: prometheus
  selector:
    matchLabels:
      prometheus: mw
  namespaceSelector:
    matchNames:
      - metrics
  endpoints:
    - port: web
      interval: 30s
      path: /metrics
