---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  namespace: prometheus
  labels:
    app: prometheus
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: prometheus
  namespaceSelector:
    matchNames:
      - prometheus
  endpoints:
    - port: web
      interval: 30s
      path: /metrics
