# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: prometheus
#   name: prometheus
#   namespace: ${NAMESPACE}
# spec:
#   type: ClusterIP
#   ports:
#     - name: http
#       port: 9090
#       targetPort: web
#   selector:
#     app: prometheus
