---
apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: mw
  name: prometheus
  namespace: prometheus
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9090
      targetPort: web
  selector:
    prometheus: mw
