{
 "title": "Deployments",
 "tags": [ "k8s-resources" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ns",
    "label": "Namespace",
    "query": "label_values(kube_deployment_metadata_generation, namespace)"
   },
   {
    "name": "deploy",
    "label": "Name",
    "query": "label_values(kube_deployment_metadata_generation{namespace=\"$ns\"}, deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$ns\",pod_name=~\"$deploy\"}[3m]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"$ns\",pod_name=~\"$deploy\"}) / 1024^3"
    }
   ]
  },
  {
   "title": "Network",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"$ns\",pod_name=~\"$deploy\"}[3m])) + sum(rate(container_network_receive_bytes_total{namespace=~\"$ns\",pod_name=~\"$deploy\"}[3m]))"
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max(kube_deployment_spec_replicas{namespace=~\"$ns\",deployment=~\"$deploy\"}) without (instance, pod)) by (job)"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(min(kube_deployment_status_replicas_available{namespace=~\"$ns\",deployment=~\"$deploy\"}) without (instance, pod)) by (job)"
    }
   ]
  },
  {
   "title": "Observed Generation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max(kube_deployment_status_observed_generation{namespace=~\"$ns\",deployment=~\"$deploy\"}) without (instance, pod)) by (job)"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max(kube_deployment_metadata_generation{deployment=~\"$ns\",namespace=~\"$deploy\"}) without (instance, pod)) by (job)"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas{deployment=~\"$deploy\",namespace=~\"$ns\"}) without (instance, pod)",
     "legendFormat": "Current: {{deployment}}"
    },
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=~\"$deploy\",namespace=~\"$ns\"}) without (instance, pod)",
     "legendFormat": "Available: {{deployment}}"
    },
    {
     "expr": "max(kube_deployment_status_replicas_unavailable{deployment=~\"$deploy\",namespace=~\"$ns\"}) without (instance, pod)",
     "legendFormat": "Unavailable: {{deployment}}"
    },
    {
     "expr": "min(kube_deployment_status_replicas_updated{deployment=~\"$deploy\",namespace=~\"$ns\"}) without (instance, pod)",
     "legendFormat": "Updated: {{deployment}}"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=~\"$deploy\",namespace=~\"$ns\"}) without (instance, pod)",
     "legendFormat": "Desired: {{deployment}}"
    }
   ]
  }
 ]
}