---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: grafana
spec:
  acme:
    config:
      - dns01:
          provider: prod-dns
        domains:
          - grafana.alexos.dev
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: grafana-tls
  commonName: grafana.alexos.dev
  dnsNames:
    - grafana.alexos.dev
