    # nginx.ingress.kubernetes.io/affinity: "cookie"
    # nginx.ingress.kubernetes.io/session-cookie-name: "GRAFANA_INGRESS"
    # nginx.ingress.kubernetes.io/session-cookie-max-age: "3600"
    # nginx.ingress.kubernetes.io/session-cookie-change-on-failure: "true"
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: grafana
spec:
  parentRefs:
  - kind: Gateway
    name: shared-gateway
    namespace: ingress
  hostnames:
  - grafana.alexos.dev
  rules:
  - backendRefs:
    - name: grafana-service
      port: 3000

