apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metrics

configurations:
- kustomizeconfig.yaml

secretGenerator:
- envs:
  - secret.tmp
  name: grafana-admin-user

resources:
- datasources.yaml
- folders.yaml
- grafana.yaml
- ingress.yaml

labels:
- includeSelectors: true
  pairs:
    app: grafana
