apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

commonLabels:
  app: grafana

secretGenerator:
- envs:
  - secret.tmp
  name: grafana-admin-user

configMapGenerator:
- files:
  - config/datasources.yaml
  name: grafana-datasources
- files:
  - config/dashboardproviders.yaml
  name: grafana-dashboard-providers
- files:
  - config/grafana.ini
  name: grafana-ini
- files:
  - dashboards/capacity-planning.json
  - dashboards/cluster-health.json
  - dashboards/mosstech.io.json
  name: grafana-dashboards

resources:
- certificate.yaml
- ingress.yaml
- pdb.yaml
- service.yaml
- service-account.yaml
- service-monitor.yaml
- stateful-set.yaml
