---
nameReference:
- kind: Secret
  version: v1
  fieldSpecs:
  - path: spec/deployment/spec/template/spec/containers/env/valueFrom/secretKeyRef/name
    version: v1beta1
    group: grafana.integreatly.org
    kind: Grafana