---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana
spec:
  jobLabel: app
  endpoints:
    - port: web
      path: /metrics
      interval: 15s
  selector:
    matchLabels:
      app: grafana
