{
 "title": "contact-handler-api",
 "tags": [ "websites" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{service=~\"contact-handler-api.*\", code!=\"\"}[5m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5,max(increase(http_request_duration_seconds_bucket{service=~\"contact-handler-api.*\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95,max(increase(http_request_duration_seconds_bucket{service=~\"contact-handler-api.*\"}[5m])) by (le))",
     "legendFormat": "p995"
    },
    {
     "expr": "histogram_quantile(1,max(increase(http_request_duration_seconds_bucket{service=~\"contact-handler-api.*\"}[5m])) by (le))",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{service=~\"contact-handler-api.*\",code!~\"[45].*\"}[1m])) / sum(rate(http_request_duration_seconds_count{service=~\"contact-handler-api.*\"}[1m]))",
     "legendFormat": "Request Success Rate"
    }
   ]
  },
  {
   "title": "% Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{service=~\"contact-handler-.*\",code=\"499\"}[5m])) / sum(rate(http_request_duration_seconds_count{service=~\"contact-handler-.*\"}[5m]))",
     "legendFormat": "499"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{service=~\"contact-handler-.*\",code=\"500\"}[5m])) / sum(rate(http_request_duration_seconds_count{service=~\"contact-handler-.*\"}[5m]))",
     "legendFormat": "500"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{service=~\"contact-handler-.*\",code=\"501\"}[5m])) / sum(rate(http_request_duration_seconds_count{service=~\"contact-handler-.*\"}[5m]))",
     "legendFormat": "501"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{service=~\"contact-handler-.*\",code=\"502\"}[5m])) / sum(rate(http_request_duration_seconds_count{service=~\"contact-handler-.*\"}[5m]))",
     "legendFormat": "502"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{service=~\"contact-handler-.*\",code=\"503\"}[5m])) / sum(rate(http_request_duration_seconds_count{service=~\"contact-handler-.*\"}[5m]))",
     "legendFormat": "503"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{service=~\"contact-handler-.*\",code=\"504\"}[5m])) / sum(rate(http_request_duration_seconds_count{service=~\"contact-handler-.*\"}[5m]))",
     "legendFormat": "504"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{service=~\"contact-handler-.*\",code=\"404\"}[5m])) / sum(rate(http_request_duration_seconds_count{service=~\"contact-handler-.*\"}[5m]))",
     "legendFormat": "404"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{service=~\"contact-handler-.*\",code=\"401\"}[5m])) / sum(rate(http_request_duration_seconds_count{service=~\"contact-handler-.*\"}[5m]))",
     "legendFormat": "401"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{service=~\"contact-handler-.*\",code=\"403\"}[5m])) / sum(rate(http_request_duration_seconds_count{service=~\"contact-handler-.*\"}[5m]))",
     "legendFormat": "403"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{service=~\"contact-handler-.*\",code=\"405\"}[5m])) / sum(rate(http_request_duration_seconds_count{service=~\"contact-handler-.*\"}[5m]))",
     "legendFormat": "405"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_info{pod=~\"contact-handler-api.*\"})",
     "legendFormat": "# of Pods"
    }
   ]
  },
  {
   "title": "Saturation - Requested CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{pod=~\"contact-handler.*\"}[1m])) by (container) / avg by(container) (label_replace (kube_pod_container_resource_requests_cpu_cores{pod=~\"contact-handler.*\"}, \"container\", \"$1\", \"container\", \"(.*)\"))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Saturation - Requested Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (container) (container_memory_usage_bytes {pod=~\"contact-handler.*\"}) / avg by (container) (label_replace(kube_pod_container_resource_requests_memory_bytes{pod=~\"contact-handler.*\"}, \"container\", \"$1\", \"container\", \"(.*)\")) * 100",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Saturation - Disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(container_fs_usage_bytes{pod=~\"contact-handler.*\"})",
     "legendFormat": "Average Usage"
    },
    {
     "expr": "max(container_fs_limit_bytes{pod=~\"contact-handler.*\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{service=~\"contact-handler.*\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(pod) (process_resident_memory_bytes{service=~\"contact-handler.*\"})",
     "legendFormat": "RSS: {{pod}}"
    },
    {
     "expr": "avg by(pod) (process_virtual_memory_bytes{service=~\"contact-handler.*\"})",
     "legendFormat": "VSS: {{pod}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(pod) (process_open_fds{service=~\"contact-handler.*\"})",
     "legendFormat": "Open FD: {{pod}}"
    }
   ]
  },
  {
   "title": "Response Time for Successful Pages",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{code=~\"[23]..\",service=~\"contact-handler.*\"}[5m])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Client Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{code=~\"4..\",service=~\"contact-handler.*\"}[5m])) by (code, path)",
     "legendFormat": "{{path}} - {{code}}"
    }
   ]
  },
  {
   "title": "Server Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{code=~\"5..\",service=~\"contact-handler.*\"}[5m])) by (code, path)",
     "legendFormat": "{{path}} - {{code}}"
    }
   ]
  }
 ]
}