{
 "title": "Ingress Controller",
 "tags": [ "websites" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Controller Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(avg_over_time(nginx_ingress_controller_nginx_process_connections{controller_class=\"nginx\",namespace=\"ingress\"}[1m]))"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(up{pod=~\"nginx-ingress-controller-.*\"})"
    }
   ]
  },
  {
   "title": "Config Reloads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_success{controller_class=\"nginx\"})"
    }
   ]
  },
  {
   "title": "Successful Reloads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(nginx_ingress_controller_config_last_reload_successful)"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Requests Per Second" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{status=~\"[2-3]..\"}[5m]))",
     "legendFormat": "2xx/3xx"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{status=~\"[4-5]..\"}[5m]))",
     "legendFormat": "4xx/5xx"
    }
   ]
  },
  {
   "title": "Certificate Expiry",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_ssl_expire_time_seconds{host!=\"_\"}) by (host) - time()",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95,max(increase(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",controller_class=\"nginx\"}[5m])) by (le, host))",
     "legendFormat": "p95 - {{host}}"
    }
   ]
  },
  {
   "title": "% Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",controller_class=\"nginx\",status=~\"4..\"}[5m])) / sum(irate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",controller_class=\"nginx\"}[5m])) ",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",controller_class=\"nginx\",status=\"5..\"}[5m])) / sum(irate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",controller_class=\"nginx\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Response Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_response_size_sum{ingress!=\"\",controller_class=\"nginx\"}) by (ingress)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Request/Response Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_request_size_sum{controller_class=\"nginx\"}[3m]))",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_response_size_sum{controller_class=\"nginx\"}[3m]))",
     "legendFormat": "Response"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_nginx_process_cpu_seconds_total{controller_class=\"nginx\"}[3m])) ",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_nginx_process_resident_memory_bytes{controller_class=\"nginx\"}) ",
     "legendFormat": "RSS Bytes"
    }
   ]
  },
  {
   "title": "Saturation - Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_nginx_process_connections) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Saturation - Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "decbytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{pod=~\"nginx-ingress-controller-.*\"})",
     "legendFormat": "Average Pod Resource Requests"
    },
    {
     "expr": "max(kube_pod_container_resource_limits_memory_bytes{pod=~\"nginx-ingress-controller-.*\"})",
     "legendFormat": "Pod Resource Limit"
    }
   ]
  },
  {
   "title": "Saturation - CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_cpu_user_seconds_total{container=\"nginx-ingress-controller\"}[1m]) * 100)",
     "legendFormat": "Average"
    },
    {
     "expr": "max(irate(container_cpu_user_seconds_total{container=\"nginx-ingress-controller\"}[1m]) * 100)",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Saturation - Disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(container_fs_usage_bytes{pod=~\"nginx-ingress-controller-.*\"})",
     "legendFormat": "Average Usage"
    },
    {
     "expr": "max(container_fs_limit_bytes{pod=~\"nginx-ingress-controller-.*\"})",
     "legendFormat": "Limit"
    }
   ]
  }
 ]
}