{
 "title": "NGINX Websites",
 "tags": [ "websites" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(nginx_http_connections, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total{pod=~\"$service-.*\",status!=\"\"}[5m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5,max(increase(nginx_http_request_duration_seconds_bucket{pod=~\"$service-.*\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95,max(increase(nginx_http_request_duration_seconds_bucket{pod=~\"$service-.*\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(1,max(increase(nginx_http_request_duration_seconds_bucket{pod=~\"$service-.*\"}[5m])) by (le))",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total{pod=~\"$service-.*\",code!~\"5.*\"}[1m])) / sum(rate(nginx_http_requests_total{pod=~\"$service-.*\"}[1m]))",
     "legendFormat": "Request Success Rate"
    }
   ]
  },
  {
   "title": "% Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total{pod=~\"$service-.*\",status=\"499\"}[5m])) / sum(rate(nginx_http_requests_total{pod=~\"$service-.*\"}[5m]))",
     "legendFormat": "499"
    },
    {
     "expr": "sum(rate(nginx_http_requests_total{pod=~\"$service-.*\",status=\"500\"}[5m])) / sum(rate(nginx_http_requests_total{pod=~\"$service-.*\"}[5m]))",
     "legendFormat": "500"
    },
    {
     "expr": "sum(rate(nginx_http_requests_total{pod=~\"$service-.*\",status=\"501\"}[5m])) / sum(rate(nginx_http_requests_total{pod=~\"$service-.*\"}[5m]))",
     "legendFormat": "501"
    },
    {
     "expr": "sum(rate(nginx_http_requests_total{pod=~\"$service-.*\",status=\"502\"}[5m])) / sum(rate(nginx_http_requests_total{pod=~\"$service-.*\"}[5m]))",
     "legendFormat": "502"
    },
    {
     "expr": "sum(rate(nginx_http_requests_total{pod=~\"$service-.*\",status=\"503\"}[5m])) / sum(rate(nginx_http_requests_total{pod=~\"$service-.*\"}[5m]))",
     "legendFormat": "503"
    },
    {
     "expr": "sum(rate(nginx_http_requests_total{pod=~\"$service-.*\",status=\"504\"}[5m])) / sum(rate(nginx_http_requests_total{pod=~\"$service-.*\"}[5m]))",
     "legendFormat": "504"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_info{pod=~\"$service-.*\"})",
     "legendFormat": "# of Pods"
    }
   ]
  },
  {
   "title": "Saturation - Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_http_connections{pod=~\"$service-.*\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Saturation - Requested CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{pod=~\"$service-.*\"}[1m])) by (container) / avg by(container) (kube_pod_container_resource_requests_cpu_cores{pod=~\"$service-.*\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Saturation - Requested Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (container) (container_memory_usage_bytes {pod=~\"$service-.*\"}) / avg by (container) (kube_pod_container_resource_requests_memory_bytes{pod=~\"$service-.*\"}) * 100",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Saturation - Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(container_fs_usage_bytes{pod=~\"$service-.*\"})",
     "legendFormat": "Average Usage"
    },
    {
     "expr": "max(container_fs_limit_bytes{pod=~\"$service-.*\"})",
     "legendFormat": "Limit"
    }
   ]
  }
 ]
}