---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-state-metrics
  namespace: metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-state-metrics
  template:
    metadata:
      labels:
        app: kube-state-metrics
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      tolerations:
      - effect: NoSchedule
        key: cloud.google.com/gke-spot
        operator: Equal
        value: "true"
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: kube-state-metrics
      containers:
        - name: kube-state-metrics
          image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.13.0
          args:
          - --custom-resource-state-config
          # this looks ... yeah. See: https://github.com/kubernetes/kube-state-metrics/blob/main/docs/customresourcestate-metrics.md#verticalpodautoscaler
          - |
              kind: CustomResourceStateMetrics
              spec:
                resources:
                  - groupVersionKind:
                      group: autoscaling.k8s.io
                      kind: "VerticalPodAutoscaler"
                      version: "v1"
                    labelsFromPath:
                      verticalpodautoscaler: [metadata, name]
                      namespace: [metadata, namespace]
                      target_kind: [spec, targetRef, kind]
                      target_name: [spec, targetRef, name]
                    # these only support first container in the Pod - see https://github.com/kubernetes/kube-state-metrics/issues/2041#issuecomment-1595809075
                    metrics:
                      # Target values
                      - name: "containerrecommendations_cpu_target"
                        help: "VPA status recommendation CPU target for first container, converted to Prometheus metric"
                        each:
                          type: Gauge
                          gauge:
                            path: [status, recommendation, containerRecommendations, "0", target, cpu]
                      - name: "containerrecommendations_memory_target"
                        help: "VPA status recommendation CPU target for first container, converted to Prometheus metric"
                        each:
                          type: Gauge
                          gauge:
                            path: [status, recommendation, containerRecommendations, "0", target, memory]
                      # Uncapped Target values
                      - name: "containerrecommendations_cpu_uncappedtarget"
                        help: "VPA status recommendation CPU uncapped target for first container, converted to Prometheus metric"
                        each:
                          type: Gauge
                          gauge:
                            path: [status, recommendation, containerRecommendations, "0", uncappedTarget, cpu]
                      - name: "containerrecommendations_memory_uncappedtarget"
                        help: "VPA status recommendation memory uncapped target for first container, converted to Prometheus metric"
                        each:
                          type: Gauge
                          gauge:
                            path: [status, recommendation, containerRecommendations, "0", uncappedTarget, memory]  
                      # Upper Bounds
                      - name: "containerrecommendations_cpu_upperbound"
                        help: "VPA status recommendation CPU upperbound for first container, converted to Prometheus metric"
                        each:
                          type: Gauge
                          gauge:
                            path: [status, recommendation, containerRecommendations, "0", upperBound, cpu]
                      - name: "containerrecommendations_memory_upperbound"
                        help: "VPA status recommendation memory upper bound for first container, converted to Prometheus metric"
                        each:
                          type: Gauge
                          gauge:
                            path: [status, recommendation, containerRecommendations, "0", upperBound, memory] 
                      # Lower Bounds
                      - name: "containerrecommendations_cpu_lowerbound"
                        help: "VPA status recommendation CPU lower bound for first container, converted to Prometheus metric"
                        each:
                          type: Gauge
                          gauge:
                            path: [status, recommendation, containerRecommendations, "0", lowerBound, cpu]
                      - name: "containerrecommendations_memory_lowerbound"
                        help: "VPA status recommendation memory lower bound for first container, converted to Prometheus metric"
                        each:
                          type: Gauge
                          gauge:
                            path: [status, recommendation, containerRecommendations, "0", lowerBound, memory]
          ports:
            - name: metrics
              containerPort: 8080
          resources:
            requests:
              memory: 50Mi
              cpu: 10m
            limits:
              memory: 100Mi
              cpu: 100m
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
