{
 "title": "alchemyst2",
 "tags": [ "websites" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{app=\"alchemyst\"}[5m]))",
     "legendFormat": "Overall"
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{app=\"alchemyst\", status!=\"\"}[5m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5,max(increase(flask_http_request_duration_seconds_bucket{app=\"alchemyst\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95,max(increase(flask_http_request_duration_seconds_bucket{app=\"alchemyst\"}[5m])) by (le))",
     "legendFormat": "p995"
    },
    {
     "expr": "histogram_quantile(1,max(increase(flask_http_request_duration_seconds_bucket{app=\"alchemyst\"}[5m])) by (le))",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{job=~\"alchemyst-(.*)\",code!~\"5.*\"}[1m])) / sum(rate(flask_http_request_total{job=~\"alchemyst-(.*)\"}[1m]))",
     "legendFormat": "Request Success Rate"
    }
   ]
  },
  {
   "title": "% Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{app=\"alchemyst\",status=\"499\"}[5m])) / sum(rate(flask_http_request_total{app=\"alchemyst\"}[5m]))",
     "legendFormat": "499"
    },
    {
     "expr": "sum(rate(flask_http_request_total{app=\"alchemyst\",status=\"500\"}[5m])) / sum(rate(flask_http_request_total{app=\"alchemyst\"}[5m]))",
     "legendFormat": "500"
    },
    {
     "expr": "sum(rate(flask_http_request_total{app=\"alchemyst\",status=\"501\"}[5m])) / sum(rate(flask_http_request_total{app=\"alchemyst\"}[5m]))",
     "legendFormat": "501"
    },
    {
     "expr": "sum(rate(flask_http_request_total{app=\"alchemyst\",status=\"502\"}[5m])) / sum(rate(flask_http_request_total{app=\"alchemyst\"}[5m]))",
     "legendFormat": "502"
    },
    {
     "expr": "sum(rate(flask_http_request_total{app=\"alchemyst\",status=\"503\"}[5m])) / sum(rate(flask_http_request_total{app=\"alchemyst\"}[5m]))",
     "legendFormat": "503"
    },
    {
     "expr": "sum(rate(flask_http_request_total{app=\"alchemyst\",status=\"504\"}[5m])) / sum(rate(flask_http_request_total{app=\"alchemyst\"}[5m]))",
     "legendFormat": "504"
    },
    {
     "expr": "sum(rate(flask_http_request_total{app=\"alchemyst\",status=\"404\"}[5m])) / sum(rate(flask_http_request_total{app=\"alchemyst\"}[5m]))",
     "legendFormat": "404"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_info{pod=~\"alchemyst-.*\"})",
     "legendFormat": "# of Pods"
    }
   ]
  },
  {
   "title": "Saturation - Requested CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{pod=~\"alchemyst-\\\\w+-\\\\w+$\"}[1m])) by (container) / avg by(container) (label_replace (kube_pod_container_resource_requests{resource=\"cpu\", pod=~\"alchemyst-\\\\w+-\\\\w+$\"}, \"container\", \"$1\", \"container\", \"(.*)\"))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Saturation - Requested Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (container) (container_memory_usage_bytes {pod=~\"alchemyst-\\\\w+-\\\\w+$\"}) / avg by (container) (label_replace(kube_pod_container_resource_requests{resource=\"memory\", pod=~\"alchemyst-\\\\w+-\\\\w+$\"}, \"container\", \"$1\", \"container\", \"(.*)\")) * 100",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Saturation - Disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(container_fs_usage_bytes{pod=~\"alchemyst.*\"})",
     "legendFormat": "Average Usage"
    },
    {
     "expr": "max(container_fs_limit_bytes{pod=~\"alchemyst.*\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{service=~\"alchemyst-.*\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(pod) (process_resident_memory_bytes{service=~\"alchemyst-.*\"})",
     "legendFormat": "RSS: {{pod}}"
    },
    {
     "expr": "avg by(pod) (process_virtual_memory_bytes{service=~\"alchemyst-.*\"})",
     "legendFormat": "VSS: {{pod}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(pod) (process_open_fds{service=~\"alchemyst-.*\"})",
     "legendFormat": "Open FD: {{pod}}"
    }
   ]
  },
  {
   "title": "Response Time for Successful Pages",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status=~\"[23]..\",app=\"alchemyst\"}[1m])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Missing Pages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status=\"404\",app=\"alchemyst\"}[1m])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}