{
 "title": "Kubernetes Capacity Planning",
 "tags": [ "k8s-cluster" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Idle CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (node_name) * 100",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "sum(node_load1) by (node_name)", "legendFormat": "load 1m: {{node_name}}" },
    { "expr": "sum(node_load5) by (node_name)", "legendFormat": "load 5m: {{node_name}}" },
    {
     "expr": "sum(node_load15) by (node_name)",
     "legendFormat": "load 15m: {{node_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes) by (node_name) - sum(node_memory_MemFree_bytes) by (node_name) - sum(node_memory_Buffers_bytes) by (node_name) - sum(node_memory_Cached_bytes) by (node_name)",
     "legendFormat": "Used: {{node_name}}"
    },
    {
     "expr": "sum(node_memory_Buffers_bytes) by (node_name)",
     "legendFormat": "Buffers: {{node_name}}"
    },
    {
     "expr": "sum(node_memory_Cached_bytes) by (node_name)",
     "legendFormat": "Cached: {{node_name}}"
    },
    {
     "expr": "sum(node_memory_MemFree_bytes) by (node_name)",
     "legendFormat": "Free: {{node_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes)  - sum(node_memory_Buffers_bytes) - sum(node_memory_Cached_bytes)) / sum(node_memory_MemTotal_bytes)) * 100"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total[5m])) by (node_name)",
     "legendFormat": "Read: {{node_name}}"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total[5m])) by (node_name)",
     "legendFormat": "Written: {{node_name}}"
    },
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total[5m])) by (node_name)",
     "legendFormat": "I/O Time: {{node_name}}"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!=\"rootfs\"}) - sum(node_filesystem_free_bytes{device!=\"rootfs\"})) / sum(node_filesystem_size_bytes{device!=\"rootfs\"}) * 100"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lo\"}[5m])) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!~\"lo\"}[5m])) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Cluster Pod Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_info) by (node_name)",
     "legendFormat": "# Pods: {{node_name}}"
    },
    {
     "expr": "sum(kube_node_status_capacity_pods) by (node_name)",
     "legendFormat": "Max  Pods: {{node_name}}"
    }
   ]
  },
  {
   "title": "Pod Utilization",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (sum(kube_node_status_capacity_pods) - sum(kube_pod_info)) / sum(kube_node_status_capacity_pods) * 100"
    }
   ]
  }
 ]
}