{
 "title": "Kubernetes Cluster Health",
 "tags": [ "k8s-cluster" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Crashlooping Pods",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(increase(kube_pod_container_status_restarts_total[1h]) > 5)"
    }
   ]
  },
  {
   "title": "Node Not Ready",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status!=\"true\"})"
    }
   ]
  },
  {
   "title": "Node Unschedulable",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)"
    }
   ]
  },
  {
   "title": "Node Memory Pressure",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Node Disk Pressure",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Pod Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kubelet_running_pods) by (node)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Container Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kubelet_running_containers) by (node)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Kubelet Operations Errors",
   "type": "timeseries",
   "description": "Rate of Kubelet Operations Errors in 5 min intervals",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_runtime_operations_errors_total[5m])) by (node)",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}