{
 "title": "photo-album",
 "tags": [ "websites" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "4GS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{service=\"photo-album\"}[5m]))",
     "legendFormat": "Overall"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{service=\"photo-album\", status!=\"\"}[5m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,max(increase(http_request_duration_seconds_bucket{service=\"photo-album\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95,max(increase(http_request_duration_seconds_bucket{service=\"photo-album\"}[5m])) by (le))",
     "legendFormat": "p995"
    },
    {
     "expr": "histogram_quantile(1,max(increase(http_request_duration_seconds_bucket{service=\"photo-album\"}[5m])) by (le))",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{service=\"photo-album\",code!~\"5.*\"}[1m])) / sum(rate(http_requests_total{service=\"photo-album\"}[1m]))",
     "legendFormat": "Request Success Rate"
    }
   ]
  },
  {
   "title": "% Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{service=\"photo-album\",status=\"499\"}[5m])) / sum(rate(http_requests_total{service=\"photo-album\"}[5m]))",
     "legendFormat": "499"
    },
    {
     "expr": "sum(rate(http_requests_total{service=\"photo-album\",status=\"500\"}[5m])) / sum(rate(http_requests_total{service=\"photo-album\"}[5m]))",
     "legendFormat": "500"
    },
    {
     "expr": "sum(rate(http_requests_total{service=\"photo-album\",status=\"501\"}[5m])) / sum(rate(http_requests_total{service=\"photo-album\"}[5m]))",
     "legendFormat": "501"
    },
    {
     "expr": "sum(rate(http_requests_total{service=\"photo-album\",status=\"502\"}[5m])) / sum(rate(http_requests_total{service=\"photo-album\"}[5m]))",
     "legendFormat": "502"
    },
    {
     "expr": "sum(rate(http_requests_total{service=\"photo-album\",status=\"503\"}[5m])) / sum(rate(http_requests_total{service=\"photo-album\"}[5m]))",
     "legendFormat": "503"
    },
    {
     "expr": "sum(rate(http_requests_total{service=\"photo-album\",status=\"504\"}[5m])) / sum(rate(http_requests_total{service=\"photo-album\"}[5m]))",
     "legendFormat": "504"
    },
    {
     "expr": "sum(rate(http_requests_total{service=\"photo-album\",status=\"404\"}[5m])) / sum(rate(http_requests_total{service=\"photo-album\"}[5m]))",
     "legendFormat": "404"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(kube_pod_info{pod=~\"photo-album-.*\"})",
     "legendFormat": "# of Pods"
    }
   ]
  },
  {
   "title": "Pages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response Time by Page",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{service=\"photo-album\"}[1m])) by (handler)",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Error Pages",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_requests_created{service=\"photo-album\",status!~\"[23]..\"}[1m])) by (handler, status)",
       "legendFormat": "{{path}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Saturation - Requested CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(rate(container_cpu_usage_seconds_total{pod=~\"photo-album-.*\"}[1m])) by (container) / avg by(container) (label_replace (kube_pod_container_resource_requests{resource=\"cpu\", pod=~\"photo-album-.*\"}, \"container\", \"$1\", \"container\", \"(.*)\"))",
       "legendFormat": "{{container_name}}"
      }
     ]
    },
    {
     "title": "Saturation - Requested Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (container) (container_memory_usage_bytes {pod=~\"photo-album-.*\"}) / avg by (container) (label_replace(kube_pod_container_resource_requests{resource=\"memory\", pod=~\"photo-album-.*\"}, \"container\", \"$1\", \"container\", \"(.*)\")) * 100",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Process CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total{service=\"photo-album\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Process Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by(pod) (process_resident_memory_bytes{service=\"photo-album\"})",
       "legendFormat": "RSS: {{pod}}"
      },
      {
       "expr": "avg by(pod) (process_virtual_memory_bytes{service=\"photo-album\"})",
       "legendFormat": "VSS: {{pod}}"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by(pod) (process_open_fds{service=\"photo-album\"})",
       "legendFormat": "Open FD: {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}