---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-operator
  name: prometheus-operator
  namespace: mw-platform
spec:
  type: ClusterIP
  ports:
  - name: http-metrics
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: prometheus-operator
